export const processShim = {
  platform: "linux",
  version: "v24.18.1",
  versions: {
    electron: "43.3.0",
    node: "24.18.1",
    chrome: "150.0.7871.212",
  },
  env: {},
  cwd: () => "/",
  nextTick: (fn, ...args) => setTimeout(() => fn(...args), 0),
  argv: [],
  type: "renderer",
  resourcesPath: "/",
  stdout: { write: (s) => console.log(s) },
  stderr: { write: (s) => console.error(s) },
  on: () => {},
  once: () => {},
  removeListener: () => {},
};
