services:
  ignis:
    build:
      context: .
      dockerfile: apps/ignis-server/Dockerfile
    ports:
      - "8085:8080"
    environment:
      - OBSIDIAN_VERSION=1.12.7
    volumes:
      - ./vaults:/vaults
      - ./data:/app/data
      - obsidian-app:/app/obsidian-app
    restart: unless-stopped
    labels:
      - traefik.http.routers.https-0-m5vzqnr71jws8v1ewvm63ouu-ignis.middlewares=gzip,authelia@file 


volumes:
  obsidian-app:
